version: "3.9"
services:
  course-postgres:
    image: postgres:15
    restart: always
    container_name: course-postgres-container
    ports:
      - "${PG_EXTERNAL_PORT}:5432"
    volumes:
      - ./:/app
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "${PG_ROOT_USER}"
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      PG_DB: "${PG_DB}"
    networks:
      - course-external
  course-php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: course-php-container
    volumes:
      - ./:/app
      - course_phpsocket:/var/run
    environment:
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      PG_DB: "${PG_DB}"
      PG_DSN: "${PG_DSN}"
    depends_on:
      - course-postgres
    networks:
      - course-external
    extra_hosts:
      - "host.docker.internal:host-gateway"
  course-nginx:
    image: nginx
    container_name: course-nginx-container
    labels:
      - traefik.http.routers.nginx-course.rule=Host(`course.loc`)
      - traefik.http.routers.nginx-course.tls=true
      - traefik.docker.network=course-external
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    volumes:
      - type: bind
        source: ./docker/nginx/course.loc.nginx.conf
        target: /etc/nginx/nginx.conf
      - ./:/app
      - type: volume
        source: course_phpsocket
        target: /var/run
        volume:
          nocopy: true
    depends_on:
      - course-php
    networks:
      - course-external

volumes:
  pgdata:
  course_phpsocket:

networks:
  course-external:
    name: course-external
    external: true
    driver: bridge
